# Workflow Name
name: 🚀 Deploy website on push

# Workflow branch defines
on:
  # If any git push event happened
  push:
    # branch is defines
    branches:
      - main
  # Pull request defines
  pull_request:
    branches:
      - main
  # workflow dispatch create workflows that are manually triggered with the new workflow_dispatch event.
  workflow_dispatch:

# Groups together all the jobs that run in the "🚀 Deploy website on push" workflow
jobs:
  # Job 1
  Job1:
    # Job 1 Name
    name: Hello World 🌐
    # This means that the job will execute on a fresh virtual machine of an Ubuntu Linux runner hosted by GitHub. 
    runs-on: ubuntu-latest
    #Groups together all the steps that run in the Job 1.
    steps:
      # The uses keyword specifies that this step will run on v2 of the actions/checkout action. 
      - uses: actions/checkout@v2
      # Execution Step name
      - name: hello world
        # The run keyword tells the job to execute a command on the runner
        run: echo "Hello World"
        # The shell script will be git bash
        shell: bash
    
  job2:
    name: Goodbye World 🌐
    runs-on: ubuntu-latest
    steps: 
      - name: goodby world
        run: echo "Goodbye World"
        shell: bash