name: Create a comment on new issues

on: 
  issues: 
    types: [opened]

jobs: 
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github issues"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with: 
          issue-number: ${{ github.event.issue.number }}
          body:
            Thanks for raise the issue, we're gonna soon fix this issue.
          reactions: '+1' 
    steps:
      - uses: wow-actions/welcome@v1
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          FIRST_ISSUE: |
            👋 @{{ author }}
             Thanks for opening your first issue here! Be sure to follow the issue template!

          FIRST_PR: |
            👋 @{{ author }}
            Thanks for opening this pull request! Please check out our contributing guidelines.

          FIRST_PR_MERGED: |
            🎉 @{{ author }}
            Congrats on merging your first pull request! We here at behavior bot are proud of you!  